### ISSUE TITLE
[Bug]: Getting tunnel server error `CERT_HAS_EXPIRED`

### ISSUE THREAD

**Issue by iamjaredwalters** [livecycle/preevy#219]
### What happened?

`preevy up` fails where it previously succeeded. Running the following command:

```bash
preevy up --id pr-3456 -f docker-compose.preview.yml
✔ Loading compose file: docker-compose.preview.yml
✔ Got tunneling key from profile
⠼ Tunnel server: Connecting...error checking connection Error: certificate has expired
    at TLSSocket.onConnectSecure (node:_tls_wrap:1545:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:743:12) {
  code: 'CERT_HAS_EXPIRED'
}
✖ Tunnel server: Connecting...
    Error: Cannot connect to ssh+tls://livecycle.run: certificate has expired
```

### Add screenshots

Running `preevy up -D` shows this output:

```bash
preevy up -D --id pr-3456 -f docker-compose.preview.yml
✔ Loading compose file: docker-compose.preview.yml
✔ Got tunneling key from profile
⠙ Tunnel server: Connecting...connecting to tunnel server ssh with config {
  hostname: 'livecycle.run',
  port: 443,
  isTls: true,
  clientPrivateKey: '*** REDACTED ***',
  username: 'jared',
  tlsServerName: undefined,
  insecureSkipVerify: false,
  knownServerPublicKeys: [
    <Buffer 73 73 68 2d 72 73 61 20 41 41 41 41 42 33 4e 7a 61 43 31 79 63 32 45 41 41 41 41 44 41 51 41 42 41 41 41 43 41 51 44 6a 38 4b 43 6a 6b 48 50 34 6f 48 ... 674 more bytes>
  ],
  clientPublicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID1y5HQth3LKL0vlPHv6VFA3fZsQNjWKsTEJfpDBx7Lm'
}
⠼ Tunnel server: Connecting...error checking connection Error: certificate has expired
    at TLSSocket.onConnectSecure (node:_tls_wrap:1545:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:743:12) {
  code: 'CERT_HAS_EXPIRED'
}
✖ Tunnel server: Connecting...
Error: Cannot connect to ssh+tls://livecycle.run: certificate has expired
    at attempt (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@preevy/core/src/tunneling/tunnel-server-client.ts:93:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at connectToTunnelServerSsh (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@preevy/core/src/tunneling/tunnel-server-client.ts:111:10)
    at connectToTunnelServerSsh (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/src/tunnel-server-client.ts:32:28)
    at opPrefix (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/src/commands/up.ts:81:62)
    at withSpinner (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@preevy/core/src/spinner.ts:35:20)
    at Up.run (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/src/commands/up.ts:78:46)
    at Up._run (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@oclif/core/lib/command.js:117:22)
    at Config.runCommand (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@oclif/core/lib/config/config.js:314:25)
    at Object.run (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@oclif/core/lib/main.js:89:16)
```

### Steps to reproduce the behavior

Unsure. Just started happening after a couple days of use on the same project.

### Expected behavior

Would be nice to provide steps to rectify the issue in the output

### What OS are you seeing the problem on?

MacOS

### Additional context

Using the AWS Lightsail driver

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by Yshayy** [comment]
Hey @iamjaredwalters, thanks for reaching out.
Our public instance had a certificate issue, it's now refreshed, it should work now.
