### ISSUE TITLE
[Bug]: TooManyRequestsException: Rate exceeded

### ISSUE THREAD

**Issue by iamjaredwalters** [livecycle/preevy#224]
### What happened?

All preevy commands returning `TooManyRequestsException: Rate exceeded` error. Especially confusing because I've not used preevy for a few days.

### Add screenshots

```bash
$ preevy up -D --id pr-4444 -f docker-compose.preview.yml
✔ Loading compose file: docker-compose.preview.yml
✖ Getting tunneling key from profile...
TooManyRequestsException: Rate exceeded
    at Function.from (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@smithy/property-provider/dist-cjs/ProviderError.js:12:30)
    at resolveSSOCredentials (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/resolveSSOCredentials.js:46:60)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@smithy/property-provider/dist-cjs/chain.js:12:33
    at coalesceProvider (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)
    at SignatureV4.credentialProvider (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@smithy/property-provider/dist-cjs/memoize.js:33:24)
    at SignatureV4.signRequest (/Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@smithy/signature-v4/dist-cjs/SignatureV4.js:106:29)
    at /Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:16:18
    at /Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at /Users/jared/.nvm/versions/node/v18.13.0/lib/node_modules/preevy/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

### Steps to reproduce the behavior

Run `preevy up` in an existing (and previously successful) environment.

### Expected behavior

Expecting successful commands

### Additional context

Using AWS Lightsail driver

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by iamjaredwalters** [comment]
Appears to be related to the ongoing [AWS IAM outage](https://health.aws.amazon.com/health/status). Will re-open should it persists beyond the outage.
